---
title: "R Notebook"
output: html_notebook
---

```{r message = F}
library(tidyverse)
library(ggthemes)
library(gganimate)
library(gifski)
library(groupdata2)
library(viridis)
```

```{r}
bert_dir <- '../behavioral_experiment/stimuli/bert/'
wiki_dir <- '../behavioral_experiment/stimuli/wiki/'

initial_sentences <- read_csv('../behavioral_experiment/stimuli/initial_sentences.csv') %>%
  mutate(initial_sentence = str_to_lower(initial_sentence)) %>%
  rename(initial_prob = prob)

wiki_stims <- bind_rows(
  read_csv(paste0(wiki_dir, '12TokenSents.csv')) %>% mutate(sent_length = 'short', source = 'wiki'),
  read_csv(paste0(wiki_dir, '21TokenSents.csv')) %>% mutate(sent_length = 'medium', source = 'wiki'),
  read_csv(paste0(wiki_dir, '37TokenSents.csv')) %>% mutate(sent_length = 'long', source = 'wiki')
)

bert_stims <- bind_rows(
  read_csv(paste0(bert_dir, '12TokenSents.csv')) %>% mutate(sent_length = 'short', source = 'bert'),
  read_csv(paste0(bert_dir, '21TokenSents.csv')) %>% mutate(sent_length = 'medium', source = 'bert'),
  read_csv(paste0(bert_dir, '37TokenSents.csv')) %>% mutate(sent_length = 'long', source = 'bert')
) 
```

```{r}
# sample subset of bert_stims for hand cleaning
samples <- bert_stims %>%
  mutate(initial_sentence = str_to_lower(initial_sentence)) %>%
  left_join(initial_sentences, by = c('initial_sentence')) %>%
  group_by(sent_length) %>%
  mutate(step = substep + (max(substep) + 1) * iter_num,
         step_size = (max(substep) + 1) * 5,
         num_periods = str_count(sentence, fixed("."))) %>%
  filter(num_periods == 1) %>%
  group_by(sent_length, chain_num, sentence_num) %>%
  filter(step %in% c(0, 2^(0:9), max(step), max(step) - 100*step_size, max(step) - 200*step_size)) %>%
  mutate(sentence = gsub('[CLS] ', '', sentence, fixed = T),
         sentence = gsub(' [SEP]', '', sentence, fixed = T)) %>%
  select(sentence_num, chain_num, iter_num, sentence, prob,  step, prob_class, source, sent_length) %>%
  ungroup() %>%
  distinct(across(-chain_num), .keep_all = TRUE)

write_csv(samples, file = '../behavioral_experiment/stimuli/possible_bert_sentences_uncleaned.csv')
```


```{r}
early_sentences <- read_csv('../behavioral_experiment/stimuli/possible_bert_sentences_cleaned.csv') %>%
  filter(step < 1000) %>%
  group_by(sentence_num, sent_length, step) %>%
  sample_n(1) %>%
  mutate(phase = 'early')

late_sentences <- read_csv('../behavioral_experiment/stimuli/possible_bert_sentences_cleaned.csv') %>%
  filter(step > 1000) %>%
  group_by(sentence_num, sent_length, chain_num) %>%
  sample_n(1) %>%
  mutate(phase = 'late')

wiki_sentences <- wiki_stims %>%
  group_by(sent_length, source) %>%
  sample_n(50) %>%
  rename(prob = prob_1) %>%
  select(sentence, prob, sent_length, source) %>%
  left_join(initial_sentences %>%
      group_by(prob_class,sent_length) %>%
      summarize(prob = mean(initial_prob)) %>%
      spread(prob_class, prob) %>%
      mutate(halfway_point = (low + high)/2)) %>%
  mutate(sentence_num = row_number(), chain_num = 0, iter_num = 0, step = 0, phase='wiki',
         prob_class = ifelse(prob < halfway_point, 'low', 'high')) %>%
  select(-high, -low, -halfway_point)
```

```{r}
out <- bind_rows(
  wiki_sentences, late_sentences, early_sentences
  ) %>%
  unite(id, chain_num, iter_num) %>%
  ungroup() %>%
  groupdata2::fold(k = 30, cat_col = c('sent_length', 'source', 'phase', 'prob_class', 'sentence_num'))

write_csv(out, file = '../behavioral_experiment/stimuli/grouped_stims_for_mongo.csv')
```

# Visualize chains

```{r}
tsne <- read_csv('./tsne_out.csv') %>%
  filter(edit_rate > 0) %>%
  mutate(step = substep + (max(substep) + 1) * iter_num) %>%
  select(sentence, step, x_tsne, y_tsne) %>%
  mutate(prev_x = lag(x_tsne) ,
         prev_y = lag(y_tsne))

tsne %>%
  ggplot(aes(x = x_tsne, y = y_tsne, color = step)) +
    geom_point(size = .5) +
    geom_segment(aes(xend = prev_x, yend = prev_y), 
                 arrow.fill = NULL) +
                 # arrow = arrow(length = unit(0.30,"cm"), 
                 #               angle = 15, 
                 #               type = "closed")) +
    # uncomment this line to see text labels
    #geom_text(aes(label=sentence), size = 1)+
    theme_few(20) +
    scale_shape_manual(values = c(21)) +
    scale_alpha_continuous(range = c(0.5, 1))+
    scale_color_gradientn(colours = viridis(5))+
    theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank()) +
    labs(x = "", y = "") +
    guides(color = F, shape = F, alpha = F) +
    theme(aspect.ratio = 1)  #+

ggsave(filename = 'tsne.pdf',
       width = 20, height = 20)

```

## make a tsne animation

```{r}
out <- tsne %>%
  ggplot(aes(x = x_tsne, y = y_tsne, color = step)) +
    geom_point() +
    geom_segment(aes(xend = prev_x, yend = prev_y), arrow.fill = NULL) +
    theme_few(12) +
    scale_shape_manual(values = c(21)) +
    scale_alpha_continuous(range = c(0.5, 1))+
    scale_color_gradientn(colours = viridis(5))+
    guides(color = F, shape = F, alpha = F) +
    theme(aspect.ratio = 1)  +
    labs(title = '{tsne %>% filter(step == closest_state) %>% pull(sentence)}', x = "", y = "") +
    theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank()) +
    #transition_time(step) +
    transition_states(step, transition_length = 0, state_length = .1) +
    shadow_mark() 

#animate(out, nframes = 1000, renderer = gifski_renderer('tsne-animation.gif'))
a <- animate(out, nframes = 1000, renderer = av_renderer('tsne.mp4'))
anim_save(filename = "tsne-animation.mp4")

```