---
title: "R Notebook"
output: html_notebook
---

# Imports

Import dependencies

```{r}
library(tidyverse)
library(tidyboot)
library(here)
library(viridis)
library(ggthemes)
```

```{r}
d.chains <- read_csv(here('FrozenBertDataNew/BehavData/10_2000/21TokenSents/bert_new_gibbs_random_input_1.csv')) %>%
  filter(step==0)
```

Squeeze

```{r}
d.chain.plot <- d.chains %>%
  group_by(initial_sentence) %>%
  mutate(prob_class = ifelse(sentence_num > 4, 'high', 'low')) %>%
  filter(iter_num%%25==0) %>%
  filter(iter_num < 501)

d.chain.plot %>%
  group_by(prob_class, iter_num) %>%
  tidyboot_mean(prob) %>%
  ggplot(aes(x = iter_num, y = empirical_stat, color = prob_class)) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_errorbar(aes(ymin =ci_lower, ymax = ci_upper), size = 1, width = 0) +
    stat_smooth(aes(y = prob, group = interaction(chain_num, sentence_num)), 
                data = d.chain.plot, geom="line", alpha=0.1, size=1, span=.5) +
    theme_few() +
    theme(aspect.ratio = 1, legend.position = 'none') +
    labs(y = 'sentence score',
         x = 'epoch')

ggsave('squeeze.pdf', width = 3, height = 3, units = 'in')
```

